### ISSUE TITLE
Export to FC: Verify New Workspace is New

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/cgp-boardwalk#10]
In the Export to FireCloud dialog, the user can either select an existing workspace or specify the name of a new workspace.

We should validate client-side that the new workspace the user types in is actually new, i.e., they don't accidentally type in the name of an existing workspace.

**Comment by cricketsloan** [comment]
This comes from: https://github.com/DataBiosphere/boardwalk/issues/9

**Comment by coverbeck** [comment]
This will become moot once we switch to use FireCloud UI for Export, #11, so closing.
