### ISSUE TITLE
Handle Lambda Timeout in Export to FireCloud

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/cgp-boardwalk#8]
The connection to a lambda times out after 30 seconds. But the lambda will continue to processing for up to 300 (?) seconds.

While I haven't seen a timeout yet, I worry that with bigger datasets it could happen.

If the browser makes a call and it times out, the UI should display a message indicating that it timed out but may eventually suceed.

moved from ticket https://github.com/DataBiosphere/boardwalk/issues/7

**Comment by coverbeck** [comment]
This will become moot as we redirect to FireCloud to handle the import, #11, so closing this.
